start_x_pos_range: [-450, 50.0]
start_y_pos_range: [300.0, 600.0]
start_x_vel_range: [0, 10.0]
start_y_vel_range: [-20.0, 20.0]
number_boids: 50 

animation_frame_number: 50
animation_time_interval: 50

nearby_distance: 10
match_speed_distance: 100

velocity_scale_factor: 0.01
velocity_match_factor: 0.125

x_limits: [-500, 1500]
y_limits: [-500, 1500]